/**
 * This file was generated by kysely-codegen.
 * Please do not edit it manually.
 */

import type { ColumnType } from "kysely";

export type Generated<T> = T extends ColumnType<infer S, infer I, infer U>
  ? ColumnType<S, I | undefined, U>
  : ColumnType<T, T | undefined, T>;

// BIGINT columns are parsed to safe integers by pg-types.ts; see configurePgTypes.
export type Int8 = ColumnType<number, number, number>;

export type Json = JsonValue;

export type JsonArray = JsonValue[];

export type JsonObject = {
  [x: string]: JsonValue | undefined;
};

export type JsonPrimitive = boolean | number | string | null;

export type JsonValue = JsonArray | JsonObject | JsonPrimitive;

export type Numeric = ColumnType<string, number | string, number | string>;

export type Timestamp = ColumnType<Date, Date | string, Date | string>;

export interface Administrator {
  created_at: Generated<Timestamp>;
  email: string;
  id: Generated<string>;
  language: Generated<string>;
  last_sign_in_at: Timestamp | null;
  locked_until: Timestamp | null;
  name: string;
  password_hash: string;
  status: Generated<string>;
  timezone: Generated<string>;
  totp_enrolled_at: Timestamp | null;
  totp_secret_ciphertext: Buffer | null;
  updated_at: Generated<Timestamp>;
}

export interface AdminSession {
  administrator_id: string;
  client_description: Generated<string>;
  expires_at: Timestamp;
  id: Generated<string>;
  issued_at: Generated<Timestamp>;
  last_seen_at: Generated<Timestamp>;
  origin_address: string;
  revoked_at: Timestamp | null;
  revoked_by: string | null;
  second_factor_at: Timestamp | null;
  token_hash: Buffer;
}

export interface Alert {
  acknowledged_at: Timestamp | null;
  acknowledged_by: string | null;
  action_reference: string;
  category: string;
  cleared_at: Timestamp | null;
  detail: Generated<Json>;
  escalated_at: Timestamp | null;
  fingerprint: string;
  id: Generated<string>;
  last_notified_at: Timestamp | null;
  last_seen_at: Generated<Timestamp>;
  occurrence_count: Generated<number>;
  project_id: string | null;
  raised_at: Generated<Timestamp>;
  severity: string;
  status: Generated<string>;
  subject_reference: string;
  subject_type: string;
  title: string;
}

export interface AlertDelivery {
  address: string;
  alert_id: string;
  attempt: Generated<number>;
  channel: string;
  group_id: string | null;
  id: Generated<Int8>;
  kind: string;
  response: string | null;
  sent_at: Generated<Timestamp>;
  status: string;
}

export interface AlertGroup {
  active: Generated<boolean>;
  description: Generated<string>;
  id: Generated<string>;
  name: string;
}

export interface AlertGroupAddress {
  active: Generated<boolean>;
  address: string;
  channel: string;
  group_id: string;
}

export interface AlertGroupMember {
  administrator_id: string;
  group_id: string;
}

export interface AlertPolicy {
  acknowledgement_required: Generated<boolean>;
  category: string;
  escalation_group_id: string | null;
  escalation_minutes: Generated<number>;
  minimum_severity: Generated<string>;
  updated_at: Generated<Timestamp>;
}

export interface AlertPolicyGroup {
  category: string;
  group_id: string;
}

export interface ApprovalRequest {
  amount: Int8 | null;
  created_at: Generated<Timestamp>;
  currency_code: string | null;
  decided_at: Timestamp | null;
  decided_by: string | null;
  decision_reason: string | null;
  id: Generated<string>;
  initiated_by: string;
  justification: string;
  status: Generated<string>;
  subject: Json;
  summary: string;
  type: string;
}

export interface AuditRecord {
  action: string;
  actor_id: string | null;
  approved_by: string | null;
  confirmation_id: string | null;
  correlation_id: string | null;
  id: Generated<Int8>;
  new_state: Json | null;
  occurred_at: Generated<Timestamp>;
  prior_state: Json | null;
  subject_id: string;
  subject_type: string;
}

export interface AuthenticationEvent {
  administrator_id: string | null;
  client_description: Generated<string>;
  email_presented: string;
  id: Generated<Int8>;
  occurred_at: Generated<Timestamp>;
  origin_address: string;
  outcome: string;
  reason: Generated<string>;
}

export interface Cashout {
  amount: Int8;
  approved_by: string | null;
  confirmed_at: Timestamp | null;
  created_at: Generated<Timestamp>;
  currency_code: string;
  destination_reference: string;
  float_account_id: string;
  id: Generated<string>;
  initiated_by: string;
  ledger_entry_id: string | null;
  liquidity_remainder: Int8;
  settlement_account_id: string;
  solvency_remainder: Int8;
  status: Generated<string>;
  supporting_document: string | null;
}

export interface CircuitBreaker {
  failure_count: Generated<number>;
  last_probe_at: Timestamp | null;
  opened_at: Timestamp | null;
  provider_account_id: string;
  state: Generated<string>;
  updated_at: Generated<Timestamp>;
  window_started_at: Timestamp | null;
}

export interface Country {
  active: Generated<boolean>;
  code: string;
  created_at: Generated<Timestamp>;
  dialling_prefix: string;
  iso3: string;
  name: string;
}

export interface CountryCurrency {
  country_code: string;
  currency_code: string;
}

export interface Currency {
  code: string;
  created_at: Generated<Timestamp>;
  exponent: number;
  name: string;
}

export interface Discrepancy {
  adjustment_posted: Generated<boolean>;
  approved_by: string | null;
  assignee_id: string | null;
  created_at: Generated<Timestamp>;
  currency_code: string | null;
  decided_at: Timestamp | null;
  decision: string | null;
  difference: Int8 | null;
  expected: Json;
  fingerprint: string;
  first_detected_at: Generated<Timestamp>;
  float_account_id: string | null;
  float_transfer_id: string | null;
  id: Generated<string>;
  last_detected_at: Generated<Timestamp>;
  observed: Json;
  provider_account_id: string;
  recurrences_after_resolution: Generated<number>;
  resolved_by: string | null;
  resolving_entry_id: string | null;
  run_id: string;
  runs_seen: Generated<number>;
  status: Generated<string>;
  subject_reference: string;
  subject_type: string;
  transaction_id: string | null;
  type: string;
}

export interface DiscrepancyComment {
  author_id: string;
  body: string;
  created_at: Generated<Timestamp>;
  discrepancy_id: string;
  id: Generated<Int8>;
}

export interface Entitlement {
  created_at: Generated<Timestamp>;
  id: Generated<string>;
  project_id: string;
  route_id: string;
}

export interface EntitlementVersion {
  active: Generated<boolean>;
  count_24h: number;
  count_30d: number;
  created_at: Generated<Timestamp>;
  created_by: string | null;
  entitlement_id: string;
  id: Generated<string>;
  maximum_amount: Int8 | null;
  minimum_amount: Int8 | null;
  note: string;
  platform_fee_bearer: string | null;
  platform_fee_bps: number | null;
  platform_fee_fixed: Int8 | null;
  processing_fee_bearer: string | null;
  processing_fee_bps: number | null;
  processing_fee_fixed: Int8 | null;
  sequence: number;
  valid_from: Generated<Timestamp>;
  valid_to: Timestamp | null;
  value_24h: Int8;
  value_30d: Int8;
}

export interface ExchangeRate {
  base_currency: string;
  created_at: Generated<Timestamp>;
  effective_date: Timestamp;
  id: Generated<string>;
  quote_currency: string;
  rate: Numeric;
  source: string;
}

export interface ExportRecord {
  administrator_id: string;
  created_at: Generated<Timestamp>;
  environment: string;
  filters: Json;
  id: Generated<string>;
  row_count: number;
  signature: string;
  subject: string;
}

export interface FloatThreshold {
  account_id: string;
  minimum_hours: Generated<number>;
  override_amount: Int8 | null;
  target_hours: Generated<number>;
  updated_at: Generated<Timestamp>;
  updated_by: string | null;
}

export interface FloatTransfer {
  amount: Int8;
  confirmed_at: Timestamp | null;
  confirming_run_id: string | null;
  created_at: Generated<Timestamp>;
  currency_code: string;
  destination_account_id: string;
  execution_path: string;
  id: Generated<string>;
  initiated_by: string;
  ledger_entry_id: string | null;
  note: Generated<string>;
  provider_account_id: string;
  provider_fee: Generated<Int8>;
  provider_reference: string | null;
  source_account_id: string;
  status: Generated<string>;
}

export interface Job {
  attempts: Generated<number>;
  created_at: Generated<Timestamp>;
  dedupe_key: string | null;
  finished_at: Timestamp | null;
  id: Generated<Int8>;
  kind: string;
  last_error: string | null;
  locked_at: Timestamp | null;
  locked_by: string | null;
  max_attempts: Generated<number>;
  payload: Generated<Json>;
  run_at: Generated<Timestamp>;
  status: Generated<string>;
}

export interface LedgerAccount {
  country_code: string | null;
  created_at: Generated<Timestamp>;
  currency_code: string;
  direction: string | null;
  id: Generated<string>;
  project_id: string | null;
  provider_account_id: string | null;
  settlement_destination: string | null;
  type: string;
}

export interface LedgerCheckpoint {
  account_id: string;
  balance: Int8;
  created_at: Generated<Timestamp>;
  id: Generated<Int8>;
  through_posting_id: Int8;
}

export interface LedgerEntry {
  author_id: string | null;
  created_at: Generated<Timestamp>;
  discrepancy_id: string | null;
  entry_type: string;
  id: Generated<string>;
  justification: string | null;
  occurred_at: Generated<Timestamp>;
  reference: string | null;
  reverses_entry_id: string | null;
  transaction_id: string | null;
}

export interface LedgerPosting {
  account_id: string;
  amount: Int8;
  entry_id: string;
  id: Generated<Int8>;
  side: string;
}

export interface NotificationDelivery {
  attempt: Generated<number>;
  created_at: Generated<Timestamp>;
  delivered_at: Timestamp | null;
  endpoint_id: string;
  event_id: string;
  event_type: string;
  id: Generated<string>;
  max_attempts: Generated<number>;
  next_attempt_at: Generated<Timestamp>;
  payload: Json;
  replayed_by: string | null;
  replayed_from: string | null;
  status: Generated<string>;
  transaction_id: string;
}

export interface NotificationDeliveryAttempt {
  attempt: number;
  attempted_at: Generated<Timestamp>;
  delivery_id: string;
  duration_ms: number | null;
  error: string | null;
  id: Generated<Int8>;
  response_body: string | null;
  response_status: number | null;
}

export interface OperationConfirmation {
  administrator_id: string;
  attempts: Generated<number>;
  code_hash: Buffer;
  consumed_at: Timestamp | null;
  expires_at: Timestamp;
  fingerprint: string;
  id: Generated<string>;
  issued_at: Generated<Timestamp>;
  operation_type: string;
  outcome: Generated<string>;
  subject_reference: Generated<string>;
}

export interface OriginRefusal {
  credential_key: string;
  id: Generated<Int8>;
  occurred_at: Generated<Timestamp>;
  origin_address: string;
  project_id: string | null;
}

export interface PaymentMethod {
  code: string;
  created_at: Generated<Timestamp>;
  name: string;
}

export interface PlatformSetting {
  key: string;
  updated_at: Generated<Timestamp>;
  updated_by: string | null;
  value: Json;
}

export interface Preview {
  binding_id: string | null;
  charged_amount: Int8;
  confirmed_at: Timestamp | null;
  correlation_id: string;
  counterparty_email: string | null;
  counterparty_name: string | null;
  created_at: Generated<Timestamp>;
  currency_code: string;
  direction: string;
  entitlement_version_id: string;
  expected_provider_fee: Int8;
  expires_at: Timestamp;
  fee_rounding_remainder: Generated<Json>;
  id: Generated<string>;
  limits_snapshot: Json;
  metadata: Generated<Json>;
  msisdn_ciphertext: Buffer;
  msisdn_index: Buffer;
  msisdn_masked: string;
  payer_action: string;
  platform_fee: Int8;
  platform_fee_bearer: string;
  processing_fee: Int8;
  processing_fee_bearer: string;
  project_id: string;
  project_reference: string;
  reference: string;
  requested_amount: Int8;
  route_id: string;
  route_version_id: string;
  settled_amount: Int8;
  status: Generated<string>;
  terms_snapshot: Json;
  transaction_id: string | null;
}

export interface Project {
  code: string;
  created_at: Generated<Timestamp>;
  created_by: string | null;
  id: Generated<string>;
  name: string;
  status: Generated<string>;
  updated_at: Generated<Timestamp>;
}

export interface ProjectCredential {
  deleted_at: Timestamp | null;
  deleted_by: string | null;
  id: Generated<string>;
  issued_at: Generated<Timestamp>;
  issued_by: string | null;
  key: string;
  project_id: string;
  revoked_at: Timestamp | null;
  revoked_by: string | null;
  revoked_reason: string | null;
  role: string;
  scopes: string[];
  secret_hash: string;
  status: Generated<string>;
}

export interface ProjectNotificationEndpoint {
  active: Generated<boolean>;
  created_at: Generated<Timestamp>;
  created_by: string | null;
  id: Generated<string>;
  name: Generated<string>;
  project_id: string;
  signing_secret_ciphertext: Buffer;
  updated_at: Generated<Timestamp>;
  url: string;
  verified_at: Timestamp | null;
}

export interface ProjectOrigin {
  active: Generated<boolean>;
  cidr: string;
  created_at: Generated<Timestamp>;
  created_by: string | null;
  description: Generated<string>;
  id: Generated<string>;
  project_id: string;
}

export interface ProjectToken {
  credential_id: string;
  expires_at: Timestamp;
  id: Generated<string>;
  issued_at: Generated<Timestamp>;
  origin_address: string;
  revoked_at: Timestamp | null;
  token_hash: Buffer;
}

export interface Provider {
  adapter_key: string;
  code: string;
  name: string;
}

export interface ProviderAccount {
  base_url: string;
  created_at: Generated<Timestamp>;
  credential_ciphertext: Buffer | null;
  has_test_environment: Generated<boolean>;
  id: Generated<string>;
  name: string;
  provider_code: string;
  statement_format: string | null;
  status: Generated<string>;
  supports_listing: Generated<boolean>;
  supports_transfers: Generated<boolean>;
  suspended_at: Timestamp | null;
  suspended_by: string | null;
  updated_at: Generated<Timestamp>;
  webhook_secret_ciphertext: Buffer | null;
}

export interface ProviderAccountCapability {
  country_code: string;
  currency_code: string;
  direction: string;
  payment_method_code: string;
  provider_account_id: string;
}

export interface ProviderNotificationReceipt {
  event_key: string;
  payload_id: string | null;
  provider_account_id: string;
  provider_reference: string;
  received_at: Generated<Timestamp>;
}

export interface ProviderPayload {
  body: Json;
  correlation_id: string | null;
  created_at: Generated<Timestamp>;
  flow: string;
  id: Generated<string>;
  kind: string;
  provider_account_id: string | null;
  transaction_id: string | null;
}

export interface RateChangeSet {
  agreement_reference: string | null;
  created_at: Generated<Timestamp>;
  created_by: string | null;
  effective_at: Timestamp;
  id: Generated<string>;
  note: string;
}

export interface RateLimitWindow {
  count: Generated<number>;
  key: string;
  window_start: Timestamp;
}

export interface ReconciliationRun {
  discrepancies_raised: Generated<number>;
  error: string | null;
  finished_at: Timestamp | null;
  id: Generated<string>;
  mode: string;
  period_end: Timestamp;
  period_start: Timestamp;
  provider_account_id: string;
  records_compared: Generated<number>;
  started_at: Generated<Timestamp>;
  started_by: string | null;
  statement_import_id: string | null;
  status: Generated<string>;
  summary: Generated<Json>;
}

export interface Role {
  created_at: Generated<Timestamp>;
  description: Generated<string>;
  id: Generated<string>;
  name: string;
  seeded: Generated<boolean>;
}

export interface RoleAssignment {
  administrator_id: string;
  created_at: Generated<Timestamp>;
  granted_by: string | null;
  id: Generated<string>;
  role_id: string;
  scope_type: string;
}

export interface RoleAssignmentScope {
  assignment_id: string;
  project_id: string | null;
  provider_account_id: string | null;
}

export interface RolePermission {
  permission_key: string;
  role_id: string;
}

export interface Route {
  country_code: string;
  created_at: Generated<Timestamp>;
  currency_code: string;
  direction: string;
  id: Generated<string>;
  payment_method_code: string;
}

export interface RouteBinding {
  enabled: Generated<boolean>;
  expected_fee_bps: number;
  expected_fee_fixed: Generated<Int8>;
  id: Generated<string>;
  maximum_amount: Int8 | null;
  minimum_amount: Int8 | null;
  priority: number;
  provider_account_id: string;
  route_version_id: string;
  terms_status: Generated<string>;
}

export interface RouteVersion {
  active: Generated<boolean>;
  browser_required: Generated<boolean>;
  created_at: Generated<Timestamp>;
  created_by: string | null;
  disbursement_fallback: Generated<boolean>;
  fingerprint: string;
  id: Generated<string>;
  maximum_amount: Int8;
  minimum_amount: Int8;
  note: string;
  otp_required: Generated<boolean>;
  platform_fee_bearer: Generated<string>;
  platform_fee_bps: Generated<number>;
  platform_fee_ceiling: Int8 | null;
  platform_fee_fixed: Generated<Int8>;
  platform_fee_floor: Int8 | null;
  processing_fee_bearer: Generated<string>;
  processing_fee_bps: number;
  processing_fee_ceiling: Int8 | null;
  processing_fee_fixed: Generated<Int8>;
  processing_fee_floor: Int8 | null;
  rate_change_set_id: string | null;
  route_id: string;
  sequence: number;
  valid_from: Generated<Timestamp>;
  valid_to: Timestamp | null;
}

export interface StatementImport {
  checksum: Buffer;
  created_at: Generated<Timestamp>;
  declared_period_end: Timestamp;
  declared_period_start: Timestamp;
  filename: string;
  id: Generated<string>;
  observed_period_end: Timestamp | null;
  observed_period_start: Timestamp | null;
  provider_account_id: string;
  rejected_rows: Generated<Json>;
  row_count: Generated<number>;
  rows_rejected: Generated<number>;
  run_id: string | null;
  status: Generated<string>;
  uploaded_by: string;
}

export interface StatementRow {
  amount: Int8 | null;
  currency_code: string | null;
  direction: string | null;
  external_reference: string | null;
  fee: Int8 | null;
  import_id: string;
  occurred_at: Timestamp | null;
  provider_reference: string;
  raw: Json;
  row_number: number;
  status: string | null;
}

export interface Transaction {
  action_expires_at: Timestamp | null;
  action_url_ciphertext: Buffer | null;
  actual_provider_fee: Int8 | null;
  binding_id: string | null;
  charged_amount: Int8;
  code_attempts_remaining: number | null;
  correlation_id: string;
  counterparty_email: string | null;
  counterparty_name: string | null;
  created_at: Generated<Timestamp>;
  currency_code: string;
  current_attempt_id: string | null;
  direction: string;
  entitlement_version_id: string;
  expected_provider_fee: Int8;
  expected_settled_amount: Int8;
  failure_reason: string | null;
  id: Generated<string>;
  limits_snapshot: Json;
  metadata: Generated<Json>;
  msisdn_ciphertext: Buffer;
  msisdn_index: Buffer;
  msisdn_masked: string;
  next_status_check_at: Timestamp | null;
  original_transaction_id: string | null;
  payer_action: string;
  platform_fee: Int8;
  platform_fee_bearer: string;
  preview_id: string;
  processing_fee: Int8;
  processing_fee_bearer: string;
  project_id: string;
  project_reference: string;
  reconciliation_status: Generated<string>;
  reference: string;
  requested_amount: Int8;
  reserved_amount: Generated<Int8>;
  route_id: string;
  route_version_id: string;
  selected_provider_account_id: string | null;
  settled_amount: Int8 | null;
  state: string;
  status_check_count: Generated<number>;
  sweep_ceiling_at: Timestamp;
  terminal_at: Timestamp | null;
  terms_snapshot: Json;
  updated_at: Generated<Timestamp>;
}

export interface TransactionAttempt {
  actual_provider_fee: Int8 | null;
  binding_id: string | null;
  binding_snapshot: Json;
  ended_at: Timestamp | null;
  failure_reason: string | null;
  id: Generated<string>;
  operator_reference: string | null;
  provider_account_id: string;
  provider_error_code: string | null;
  provider_error_message: string | null;
  provider_reference: string | null;
  request_payload_id: string | null;
  response_payload_id: string | null;
  sequence: number;
  started_at: Generated<Timestamp>;
  state: string;
  transaction_id: string;
}

export interface TransactionEvent {
  actor_id: string | null;
  detail: Generated<Json>;
  discrepancy_id: string | null;
  id: Generated<Int8>;
  new_state: string;
  occurred_at: Generated<Timestamp>;
  payload_id: string | null;
  prior_state: string | null;
  source: string;
  transaction_id: string;
}

export interface DB {
  admin_session: AdminSession;
  administrator: Administrator;
  alert: Alert;
  alert_delivery: AlertDelivery;
  alert_group: AlertGroup;
  alert_group_address: AlertGroupAddress;
  alert_group_member: AlertGroupMember;
  alert_policy: AlertPolicy;
  alert_policy_group: AlertPolicyGroup;
  approval_request: ApprovalRequest;
  audit_record: AuditRecord;
  authentication_event: AuthenticationEvent;
  cashout: Cashout;
  circuit_breaker: CircuitBreaker;
  country: Country;
  country_currency: CountryCurrency;
  currency: Currency;
  discrepancy: Discrepancy;
  discrepancy_comment: DiscrepancyComment;
  entitlement: Entitlement;
  entitlement_version: EntitlementVersion;
  exchange_rate: ExchangeRate;
  export_record: ExportRecord;
  float_threshold: FloatThreshold;
  float_transfer: FloatTransfer;
  job: Job;
  ledger_account: LedgerAccount;
  ledger_checkpoint: LedgerCheckpoint;
  ledger_entry: LedgerEntry;
  ledger_posting: LedgerPosting;
  notification_delivery: NotificationDelivery;
  notification_delivery_attempt: NotificationDeliveryAttempt;
  operation_confirmation: OperationConfirmation;
  origin_refusal: OriginRefusal;
  payment_method: PaymentMethod;
  platform_setting: PlatformSetting;
  preview: Preview;
  project: Project;
  project_credential: ProjectCredential;
  project_notification_endpoint: ProjectNotificationEndpoint;
  project_origin: ProjectOrigin;
  project_token: ProjectToken;
  provider: Provider;
  provider_account: ProviderAccount;
  provider_account_capability: ProviderAccountCapability;
  provider_notification_receipt: ProviderNotificationReceipt;
  provider_payload: ProviderPayload;
  rate_change_set: RateChangeSet;
  rate_limit_window: RateLimitWindow;
  reconciliation_run: ReconciliationRun;
  role: Role;
  role_assignment: RoleAssignment;
  role_assignment_scope: RoleAssignmentScope;
  role_permission: RolePermission;
  route: Route;
  route_binding: RouteBinding;
  route_version: RouteVersion;
  statement_import: StatementImport;
  statement_row: StatementRow;
  transaction: Transaction;
  transaction_attempt: TransactionAttempt;
  transaction_event: TransactionEvent;
}
